export const customerListProjection = {
    "customerId": 1,
    "orderGroupId": 1,
    "orderStatus": 1,
    "createdAt": 1,
    "category": 1,
    "address": 1,
    "storeCustomId": 1,
    "storeId": 1,
    "storeName": 1,
    "totalCartCost": 1,
    "totalCustomerOrderCost": 1,
    "totalItem": 1,
    "isthresholdDeliveryKm": 1,
    "storeDetails.businessCategoryId": 1,
    "storeDetails.businessName": 1,
    "storeDetails.address1": 1,
    "storeDetails.address2": 1,
    "storeDetails.logo": 1,
    "storeDetails.storeName": 1,
    "customerDetails.firstName": 1,
    "customerDetails.lastName": 1,
    "deliveryConfig.thresholdDeliveryKm": 1
}


export const storeListProjection = {
    "customerId": 1,
    "orderGroupId": 1,
    "orderStatus": 1,
    "createdAt": 1,
    "category": 1,
    "address": 1,
    "storeCustomId": 1,
    "storeId": 1,
    "storeName": 1,
    "totalCartCost": 1,
    "totalCustomerOrderCost": 1,
    "totalItem": 1,
    "storeDetails.businessCategoryId": 1,
    "storeDetails.businessName": 1,
    "storeDetails.address1": 1,
    "storeDetails.address2": 1,
    "storeDetails.logo": 1,
    "storeDetails.storeName": 1,
    "customerDetails.firstName": 1,
    "customerDetails.lastName": 1,
    "totalStoreCommisionCost": 1,
    "totalStoreOrderCost": 1
}