export enum Role {
    ADMIN = "ADMIN",
    SALES_OFFICER = "SALES_OFFICER",
    DISTRIBUTER = "DISTRIBUTER",
    MANAGER = "MANAGER",
    ACCOUNTANT = "ACCOUNTANT",
    CUSTOMER = "CUSTOMER",
    STORE = "STORE"
  }